version: '3.1'
services:
  storage-event-db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5441:5432"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq