version: '3.8'

services:
  postgres-dev:
    container_name: pixelwave-postgres-dev
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: pixelwave
      POSTGRES_USER: pixelwave
      POSTGRES_PASSWORD: pixelwave
    ports:
      - "5441:5432"

  storage-service-dev:
    build:
      context: ../service-1
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres-dev
