spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      fail-fast: 'true'
  profiles:
    active: ${PROFILE:dev}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: 'true'