spring:
  application:
    name: compression-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: 'true'
  profiles:
    active: ${PROFILE:dev}