management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: storage-service
  cloud:
    config:
      fail-fast: 'true'
  profiles:
    active: rabbit
