server.port: 8888

spring:
  application.name: config-server
  cloud.config.server:
    git:
      uri: ${CONFIG_REPO:https://github.com/FelipeLM1/pixel-wave-config-repository.git}
      searchPaths: '{application}'
management:
  endpoints:
    web:
      exposure:
        include: "*"
